// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import RedirectController from "./redirect_controller"
application.register("redirect", RedirectController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import SubscribeController from "./subscribe_controller"
application.register("subscribe", SubscribeController)
