version: '3.8'

volumes:
  bundle:
  db:
  redis:

services:
  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/

  redis:
    image: redis:7.0.3
    restart: always
    command: redis-server
    ports:
      - 6379:6379
    volumes: 
      - ./redis/:/root/redis/

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - ./node_modules:/app/node_modules
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    tty: true
    stdin_open: true
    environment:
      REDIS_URL: redis://redis:6379/1

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - ./node_modules:/app/node_modules
    tmpfs: /app/tmp
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    environment:
      REDIS_URL: redis://redis:6379/1
